/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-11-10 17:47:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import dao.DataAccess;
import servlet.Post;
import java.io.*;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class Notifications_005fAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
 Class.forName("com.mysql.jdbc.Driver"); 
      out.write("\r\n");
      out.write("    ");
//Opening connection to data in database
    Connection connection = DriverManager.getConnection("jdbc:mysql://137.158.160.145:3306/ngwphu001", "ngwphu001", "eupheyei");

    Statement statement = connection.createStatement() ;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");

        if (request.getSession().getAttribute("currentUserName") == null){
        response.sendRedirect("Login.jsp");
    }
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Post Monitor</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<!-- css -->\r\n");
      out.write("\t<link  rel=\"stylesheet\" href=\"../css/site_styles.css\" />\r\n");
      out.write("\t<link  rel=\"stylesheet\" href=\"../css/animate.css\" />\r\n");
      out.write("\t<link  rel=\"stylesheet\" href=\"../css/nav_style.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/normalize.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/admin_styles.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/forum.css\">\r\n");
      out.write("\t<!-- bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Fonts -->\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Roboto:100\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- JQuery -->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!--nav--> \r\n");
      out.write("        <script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("            var pull        = $('#pull');\r\n");
      out.write("            menu        = $('nav ul');\r\n");
      out.write("            menuHeight  = menu.height();\r\n");
      out.write("\r\n");
      out.write("            $(pull).on('click', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                menu.slideToggle();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(window).resize(function(){\r\n");
      out.write("                var w = $(window).width();\r\n");
      out.write("                if(w > 320 && menu.is(':hidden')) {\r\n");
      out.write("                    menu.removeAttr('style');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("        <script> \r\n");
      out.write("        $('#nav').affix({});\r\n");
      out.write("        </script>\r\n");
      out.write("        <!--Face book-->\r\n");
      out.write("        <script>\r\n");
      out.write("            (function(d, s, id) {\r\n");
      out.write("\t\t  var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("\t\t  if (d.getElementById(id)) return;\r\n");
      out.write("\t\t  js = d.createElement(s); js.id = id;\r\n");
      out.write("\t\t  js.src = \"//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=313231902363487\";\r\n");
      out.write("\t\t  fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("            }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("    <body style=\"line-height:1;\">\r\n");
      out.write("        <div class=\"nav-container\" style=\"position:fixed; top:0; left:0; right:0; z-index:1\">\r\n");
      out.write("            <nav class=\"clearfix\">\r\n");
      out.write("                <a href=\"../index.html\" class=\"nav-title\"><img class=\"nav-logo\" src=\"../uct-logo.png\"></a>\r\n");
      out.write("                <span class=\"header-title\" style=\"color:white;\">UCT Alumni Network</span>\r\n");
      out.write("                \r\n");
      out.write("                <ul class=\"clearfix\">\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form id=\"logout_form\" method=\"post\" action=\"../logout\">\t\r\n");
      out.write("\t\t\t\t\t<li style=\"float: right;\"><a href=\"javascript:{}\" onclick=\"document.getElementById('logout_form').submit(); return false;\"><span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span> Logout</a></li> \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" id=\"pull\">Menu</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"left-navbar\">\r\n");
      out.write("\t\t<a href=\"PendingUsers.jsp\">Pending Users</a>\r\n");
      out.write("        <a href=\"SystemUsers.jsp\">System Users</a>\r\n");
      out.write("\t\t<a href=\"RejectedUsers.jsp\">Rejected Users</a>\r\n");
      out.write("\t\t<a href=\"Post_Monitor.jsp\">Post Monitor</a>\r\n");
      out.write("\t\t<a href=\"Notifications_Admin.jsp\">Notifications</a>\r\n");
      out.write("\t\t<a href=\"Reported_Posts.jsp\">Reported Posts</a>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"page\">\r\n");
      out.write("            <div class=\"wrapper\" style=\"padding: 0px 100px;\">\r\n");
      out.write("                <div class=\"content-wrapper\">\r\n");
      out.write("                    <div class=\"content\" style= \"margin-left: auto; margin-right: auto;    overflow: hidden !important;\">\r\n");
      out.write("                    <div style=\"padding: 0px 100px;margin-top: 4%;\">\r\n");
      out.write("                    <form method=\"post\" action=\"../Notify\"  >\r\n");
      out.write("                            <div class=\"post-box\">\r\n");
      out.write("                                <div class=\"editor\">\r\n");
      out.write("                                    <div class=\"editor-header\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        <span style=\"margin-left: 36%; color: black; line-height: 2;\"> Post to Notifications</span>  \r\n");
      out.write("                                        \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    <textarea class=\"write-post\" name=\"notification\" placeholder=\"Write a Notification\"></textarea>\r\n");
      out.write("                                    <div class=\"editor-buttons\">\r\n");
      out.write("                                        <button id=\"post_button\" type=\"submit\" class=\"post-btn\" name=\"post\" value=\"posting\" >Post</button>\r\n");
      out.write("            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>              \r\n");
      out.write("                            </div>\r\n");
      out.write("                           </form> </div>\r\n");
      out.write("                    <form id=\"searchForm\" action=\"../searchNotification\" method=\"post\" class=\"form-group\" style=\"width: 100%;margin-left: 10%;\">\r\n");
      out.write("                \r\n");
      out.write("                \t\t<select class=\"marshal_details\" id=\"search-dropdown\" name=\"searcher2\" style=\"background: #ccc;visibility:hidden;\"> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ALL\" selected=\"selected\">All</option> \r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"First_Name\">First Name</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Last_Name\">Last Name</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"City\">City</option> \r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Highest_Degree_year\">Highest degree</option> \r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Current_Company\">Company name</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Occupation\">Occupation</option>\t \r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Major1\">Major</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input id=\"search-text\" type=\"text\" name=\"search2\" placeholder=\"Search by any post text\" style=\"background: #ccc;\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"icon\" id=\"search-button\"    onclick=\"onSubmitForm()\" name=\"submit\" type=\"submit\"><i class=\"glyphicon glyphicon-search\" style=\"margin-top: 3px;background: #ccc;\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("                    \r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"feeds\" style=\"padding: 0px 100px;\">\r\n");
      out.write("                              \r\n");
      out.write("                            ");

                                //values from the form search fields
                                String searcher_2= request.getSession().getAttribute("searcher2")+"";
                                		//
                                String search_2 =request.getSession().getAttribute("search2")+"";
                              	
                                
                                	if((searcher_2.equalsIgnoreCase("ALL")) ){	
                                             
                                            
                                            ResultSet resultset = null;
                                            resultset =  statement.executeQuery("select * from Notifications Where concat(ID,today,Message) like lower('%"+search_2+"%')") ;
                                            ResultSetMetaData metaData = resultset.getMetaData();
                                            
                                            if(resultset.isBeforeFirst()){
                                            	
                                	 while(resultset.next())
                                         {
                                		
                                              String id=resultset.getString(2);
                                              
                                     
      out.write("\r\n");
      out.write("                                     <div class=\"posts\">\r\n");
      out.write("                                         <div class=\"editor\">\r\n");
      out.write("                                             <div class=\"editor-header\">\r\n");
      out.write("                                             <!-- Display name of user who posted-->\r\n");
      out.write("                                             \r\n");
      out.write("                                             <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ProcessRequest\" method=\"post\">\r\n");
      out.write("\t                                        \t<label style=\"background: none!important; border: none; color: #D84D0A!important; margin-top: 1.5%; font-weight: normal; margin-left: 1.5%;\" > ");
      out.print(resultset.getString(1));
      out.write("</label>\r\n");
      out.write("\t                                        \t<button type=\"submit\" name=\"remove1\" value=\"");
      out.print(id);
      out.write("\" style=\"float: right; border: 1px solid black; color: orange; background: black; width: 23px; height: 23px; text-align: center;border-radius: 17px; z-index: 1;margin-right: -2%;\">X</button> \r\n");
      out.write("\t                                        </form>\r\n");
      out.write("                                             \r\n");
      out.write("                                             \r\n");
      out.write("                                             ");
      out.print(resultset.getString(3));
      out.write("\r\n");
      out.write("                                             </div>\r\n");
      out.write("                                             \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("                                             \r\n");
      out.write("                                             <div class=\"post-body message_frame\" style=\"color: grey;\">\r\n");
      out.write("                                             \t\r\n");
      out.write("                                             \t\t<p>");
      out.print(resultset.getString(3));
      out.write("</p>\r\n");
      out.write("                                                 \t\r\n");
      out.write("                                             </div>\r\n");
      out.write("\r\n");
      out.write("                                         </div>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                     \r\n");
      out.write("                                      ");
}}
                                      else{
      out.write("\r\n");
      out.write("                                 \r\n");
      out.write("                                \t <div class=\"posts\">\r\n");
      out.write("                                     <div class=\"editor\">\r\n");
      out.write("                                         <div class=\"editor-header\">\r\n");
      out.write("                                         <!-- Display not found message to screen-->\r\n");
      out.write("                                         \r\n");
      out.write("                                         </div>\r\n");
      out.write("                                         <div class=\"post-body message_frame\" style=\"color: grey;\">\r\n");
      out.write("                                             <p>Search \"");
      out.print(search_2);
      out.write("\" Not found</p>\r\n");
      out.write("                                             <p>Enter another search value</p>\r\n");
      out.write("                                            \r\n");
      out.write("                                         </div>\r\n");
      out.write("\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \t\t \r\n");
      out.write("                                     \r\n");
      out.write("                                \t \r\n");
      out.write("                                 ");
}
                                }
                                else if(search_2.equalsIgnoreCase("null"))
                                {
                                
                                    
                                     ResultSet resultset1 = null;
                                     resultset1 =  statement.executeQuery("Select * from Notifications") ; //gets everything from CV database
                                     if(resultset1.isBeforeFirst()){
                                      while(resultset1.next()){
                                    	  String id=resultset1.getString(2);
                                      
      out.write("\r\n");
      out.write("                                        <div class=\"posts\">\r\n");
      out.write("                                         <div class=\"editor\">\r\n");
      out.write("                                             <div class=\"editor-header\">\r\n");
      out.write("                                             <!-- Display name of user who posted-->\r\n");
      out.write("                                             \r\n");
      out.write("                                             <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ProcessRequest\" method=\"post\">\r\n");
      out.write("\t                                        \t<label style=\"background: none!important; border: none; color: #D84D0A!important; margin-top: 1.5%; font-weight: normal; margin-left: 1.5%;\" > ");
      out.print(resultset1.getString(1));
      out.write("</label>\r\n");
      out.write("\t                                        \t<button type=\"submit\" name=\"remove1\" value=\"");
      out.print(id);
      out.write("\" style=\"float: right; border: 1px solid black; color: orange; background: black; width: 23px; height: 23px; text-align: center;border-radius: 17px; z-index: 1;margin-right: -2%;\">X</button> \r\n");
      out.write("\t                                        </form>\r\n");
      out.write("                                             \r\n");
      out.write("                                             \r\n");
      out.write("                                             ");
      out.print(resultset1.getString(3));
      out.write("\r\n");
      out.write("                                             </div>\r\n");
      out.write("                                             \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("                                             \r\n");
      out.write("                                             <div class=\"post-body message_frame\" style=\"color: grey;\">\r\n");
      out.write("                                             \t\r\n");
      out.write("                                             \t\t<p>");
      out.print(resultset1.getString(3));
      out.write("</p>\r\n");
      out.write("                                                 \t\r\n");
      out.write("                                             </div>\r\n");
      out.write("\r\n");
      out.write("                                         </div>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                ");
}}}

                                 
      out.write("\r\n");
      out.write("                                     <!-- Closing connection to database -->\r\n");
      out.write("  \r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        <!-- </form>   -->                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script>\r\n");
      out.write("function onSubmitForm() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar frm = document.getElementById(\"searchForm\");\r\n");
      out.write("\t   frm.submit(); // Submit\r\n");
      out.write("\t   frm.reset();  // Reset\r\n");
      out.write("\t   return false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("                \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
