/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-10-23 20:33:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.DBUtils;
import java.io.*;
import dao.ImageAccess;
import dao.*;
import java.sql.*;

public final class UpdateProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("    <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("      <title>Update Profile</title>\r\n");
      out.write("      <!-- css -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/normalize.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/nav_style.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../css/site_styles.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/updateProfile.css\">\r\n");
      out.write("      <!-- The fonts-->\r\n");
      out.write("      <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("      <link href=\"https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Roboto:100\" rel=\"stylesheet\">\r\n");
      out.write("      <!-- JQuery -->\r\n");
      out.write("      <script src=\"../jQuery/navigation-script.js\"></script>\r\n");
      out.write("      <!-- bootstrap -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("      <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("      <!--upload link-->\r\n");
      out.write("      <script>\r\n");
      out.write("          $(function(){\r\n");
      out.write("            $(\"#upload_link\").on('click', function(e){\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                $(\"#upload:hidden\").trigger('click');\r\n");
      out.write("            });\r\n");
      out.write("            });\r\n");
      out.write("      </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("      <div class=\"nav-container\" style=\"position:fixed; top:0; left:0; right:0; z-index:1\">\r\n");
      out.write("        <nav class=\"clearfix\">\r\n");
      out.write("          <a href=\"../index.html\" class=\"nav-title\"><img class=\"nav-logo\" src=\"../uct-logo.png\"></a>\r\n");
      out.write("          <span class=\"header-title\" style=\"color:white;\">UCT Alumni Network</span>\r\n");
      out.write("          <ul class=\"clearfix\">\r\n");
      out.write("            <li><a href=\"Forum.jsp\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span> Home</a></li>\r\n");
      out.write("            <li><a href=\"CV.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> Profile</a></li>\r\n");
      out.write("            <li><a href=\"Forum.jsp\"><span class=\"glyphicon glyphicon-comment\" aria-hidden=\"true\"></span> Forum</a></li>\r\n");
      out.write("            <li><a href=\"\"><span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span> Notifications</a></li>\r\n");
      out.write("            <li><a href=\"People.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> People</a></li>            \r\n");
      out.write("            <li><a href=\"../index.html\"><span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span> Logout</a></li> \r\n");
      out.write("          </ul>\r\n");
      out.write("          <a href=\"#\" id=\"pull\">Menu</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"site-wrapper\">\r\n");
      out.write("        <div class=\"site-center\">\r\n");
      out.write("          <div class=\"fixed-wrapper\">\r\n");
      out.write("            <div class=\"fixed-content\" style=\"border-left: 1px solid gray;\">\r\n");
      out.write("              ");
 
              Connection connection = DriverManager.getConnection("jdbc:mysql://137.158.160.145:3306/ngwphu001", "ngwphu001", "eupheyei");

              Statement statement = connection.createStatement() ;
              
              String uid = request.getSession().getAttribute("currentUserID")+"";
              
              ResultSet resultset = statement.executeQuery("SELECT * from CVs WHERE ID = '"+uid+"'") ; 
              if(resultset.next()){
              String fname = resultset.getString(2);
              String lname = resultset.getString(3);
              String occupation = resultset.getString(4);
              String currentCompany = resultset.getString(5);
              String address1 = resultset.getString(6);
              String address2 = resultset.getString(7);
              String city = resultset.getString(8);
              String postalCode = resultset.getString(9);
              String phone = resultset.getString(10);
              String email = resultset.getString(11); 
              
              
              byte[] imgData = ImageAccess.displayPhoto(uid);
              
              
              if(imgData==null)
              {
            	  request.getSession().setAttribute("image_status","0");
            	  System.out.println("no image");
            	  
              }
              if(imgData!=null)
              {
            	  request.getSession().setAttribute("image_status","1");
            	  System.out.println("found image");
              }
              
              String imageStatus=request.getSession().getAttribute("image_status")+"";
              
      out.write("\r\n");
      out.write("              \r\n");
      out.write("                <form method=\"post\" action=\"../ImageUpload\" enctype=\"multipart/form-data\">\r\n");
      out.write("                    <input id=\"upload\" type=\"file\" name=\"photo\"/>\r\n");
      out.write("                    <input  type=\"button\" id=\"upload_link\" value=\"Change photo\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Save\">\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t");
if(imageStatus.equals("0")){
      out.write("\r\n");
      out.write("\t\t\t    <div class=\"profile-photo\">\r\n");
      out.write("\t\t\t      <img class=\"cv-photo\" src=\"../default-profile.png\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    ");
} 
      out.write("\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    ");
if(imageStatus.equals("1")){
      out.write("\r\n");
      out.write("\t\t\t     <div class=\"profile-photo\">\r\n");
      out.write("\t\t\t      <img class=\"cv-photo\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ImageUpload\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("              <form  action=\"../UpdateProfile\" method=\"post\" class=\"update-form\">\r\n");
      out.write("                First Name<br>\r\n");
      out.write("                <input name=\"fname\" value=\"");
      out.print(fname);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("                Last  Name<br>\r\n");
      out.write("                <input name=\"lname\" value=\"");
      out.print(lname);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("\r\n");
      out.write("                Occupation<br>\r\n");
      out.write("                <input name=\"occupation\" value=\"");
      out.print(occupation);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("\r\n");
      out.write("                <h5 style=\"text-decoration:underline;\">Work Details</h5>\r\n");
      out.write("                Company or Institution<br>\r\n");
      out.write("                <input name=\"currentCompany\" value=\"");
      out.print(currentCompany);
      out.write("\" class=\"input-box\"><br> <!-- company/institution -->\r\n");
      out.write("                Address Line 1<br>\r\n");
      out.write("                <input name=\"address1\" value=\"");
      out.print(address1);
      out.write("\" class=\"input-box\"><br> <!-- adressline1 -->\r\n");
      out.write("                Address Line 2<br>\r\n");
      out.write("                <input name=\"address2\" value=\"");
      out.print(address2);
      out.write("\" class=\"input-box\"><br>                      <!-- addressLine2 -->\r\n");
      out.write("                City<br>\r\n");
      out.write("                <input name=\"city\" value=\"");
      out.print(city);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("                Postal Code<br>\r\n");
      out.write("                <input name=\"phone\" value=\"");
      out.print(postalCode);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("                Phone<br>\r\n");
      out.write("                <input name=\"postalCode\" value=\"");
      out.print(phone);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("                Email<br>\r\n");
      out.write("                <input type=\"email\" value=\"");
      out.print(email);
      out.write("\" name=\"email\" class=\"input-box\"><br>\r\n");
      out.write("\r\n");
      out.write("                <button style=\"border: 2px solid #D84D0A; font-size:10px; border-radius:3px; margin-top:5px;\" type=\"submit\">Save changes</button>\r\n");
      out.write("              </form>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"content-offset\" style=\"border-left: 1px solid gray; border-right: 1px solid gray;\">\r\n");
      out.write("            <div class=\"content-frame\"> \r\n");
      out.write("              <div id=\"header\" class=\"row\">\r\n");
      out.write("                <div class=\"header-padding\">\r\n");
      out.write("                  <div class=\"header-content\"> <h1>Curriculum Vitae</h1></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div id=\"content\" class=\"row expand\">\r\n");
      out.write("                <div class=\"inner-padding\">  \r\n");
      out.write("                  <div class=\"inner-padding\">\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"section1\" class=\"container-fluid\">\r\n");
      out.write("                      <h3 class=\"cv-section\">Education</h3>\r\n");
      out.write("                      <!-- degree major 1 major 2 -->\r\n");
      out.write("                      <p><strong>");
      out.print(resultset.getString(12) );
      out.write(' ');
      out.print(resultset.getString(14));
      out.write(' ');
      out.print(resultset.getString(15));
      out.write("</strong> <br>\r\n");
      out.write("                        ");
      out.print(resultset.getString(13));
      out.write("<br>\r\n");
      out.write("                        <span class=\"year\">");
      out.print(resultset.getString(16));
      out.write(" </span><br> <!--  year --> \r\n");
      out.write("                        <p><strong>");
      out.print(resultset.getString(17));
      out.write("</strong> <br> <span class=\"year\">");
      out.print(resultset.getString(18));
      out.write("</span> </p>       <!-- high School year -->\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div id=\"section2\" class=\"container-fluid\">\r\n");
      out.write("                        <h3 class=\"cv-section\">Experience</h3>                     \r\n");
      out.write("                        <p><strong>");
      out.print(resultset.getString(19));
      out.write("</strong> <br>  <!-- job1 -->\r\n");
      out.write("                          ");
      out.print(resultset.getString(20));
      out.write("  <br> <!-- company1 -->\r\n");
      out.write("                          <span class=\"year\">");
      out.print(resultset.getString(21));
      out.write("</span>\r\n");
      out.write("                        </p>               \r\n");
      out.write("                        \r\n");
      out.write("                        <p><strong>");
      out.print(resultset.getString(22));
      out.write("</strong> <br> <!-- job2 -->\r\n");
      out.write("                          ");
      out.print(resultset.getString(23));
      out.write("  <br> <!-- company2 -->\r\n");
      out.write("                          <span class=\"year\">");
      out.print(resultset.getString(24));
      out.write("</span> \r\n");
      out.write("                        </p>                               \r\n");
      out.write("                        \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div id=\"section3\" class=\"container-fluid\">\r\n");
      out.write("                        <h3 class=\"cv-section\">Skills</h3>\r\n");
      out.write("                        <span class=\"skills-btn\">");
      out.print(resultset.getString(25));
      out.write("</span>           <!-- skill1 -->\r\n");
      out.write("                        <span class=\"skills-btn\">");
      out.print(resultset.getString(26));
      out.write("</span>           <!-- skill2 -->\r\n");
      out.write("                        <span class=\"skills-btn\">");
      out.print(resultset.getString(27));
      out.write("</span>           <!-- skill3 -->\r\n");
      out.write("                        <span class=\"skills-btn\">");
      out.print(resultset.getString(28));
      out.write("</span>           <!-- skill4 -->\r\n");
      out.write("                        <span class=\"skills-btn\">");
      out.print(resultset.getString(29));
      out.write("</span>           <!-- skill5 -->\r\n");
      out.write("                      </div> \r\n");
      out.write("                      <div id=\"section4\" class=\"container-fluid\">\r\n");
      out.write("                        <h3 class=\"cv-section\">References</h3>\r\n");
      out.write("                        <p>");
      out.print(resultset.getString(30));
      out.write("\r\n");
      out.write("                          <address>\r\n");
      out.write("                            <a name=\"email\" href=\"mailto:#\">");
      out.print(resultset.getString(31));
      out.write("</a>\r\n");
      out.write("                          </address>\r\n");
      out.write("                          <p>");
      out.print(resultset.getString(32));
      out.write("\r\n");
      out.write("                            <address>\r\n");
      out.write("                              <a name=\"email\" href=\"mailto:#\">");
      out.print(resultset.getString(33));
      out.write("</a>\r\n");
      out.write("                            </address>\r\n");
      out.write("                          </div> \r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </body>\r\n");
      out.write("          </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
