/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-20 12:46:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.DBUtils;
import java.io.*;
import dao.*;
import java.sql.*;

public final class UpdateCV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Update CV</title>\r\n");
      out.write("        <!-- css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/normalize.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nav_style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/site_styles.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/cv.css\">\r\n");
      out.write("        <!-- The fonts-->\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Roboto:100\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- JQuery -->\r\n");
      out.write("        <script src=\"../jQuery/navigation-script.js\"></script>\r\n");
      out.write("        <!-- bootstrap -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"nav-container\" style=\"position:fixed; top:0; left:0; right:0; z-index:1\">\r\n");
      out.write("            <nav class=\"clearfix\">\r\n");
      out.write("                <a href=\"../index.html\" class=\"nav-title\"><img class=\"nav-logo\" src=\"../uct-logo.png\"></a>\r\n");
      out.write("                <span class=\"header-title\" style=\"color:white;\">UCT Alumni Network</span>\r\n");
      out.write("                <ul class=\"clearfix\">\r\n");
      out.write("                    <li><a href=\"../index.html\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span> Home</a></li>\r\n");
      out.write("                    <li><a href=\"CV.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> Profile</a></li>\r\n");
      out.write("                    <li><a href=\"Forum.jsp\"><span class=\"glyphicon glyphicon-comment\" aria-hidden=\"true\"></span> Forum</a></li>\r\n");
      out.write("                    <li><a href=\"\"><span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span> Notifications</a></li>\r\n");
      out.write("                    <li><a href=\"People.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> People</a></li>            \r\n");
      out.write("                    <li><a href=\"../index.html\"><span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span> Logout</a></li> \r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" id=\"pull\">Menu</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"site-wrapper\">\r\n");
      out.write("          <div class=\"site-center\">\r\n");
      out.write("            <div class=\"fixed-wrapper\">\r\n");
      out.write("              <div class=\"fixed-content\">\r\n");
      out.write("                <div class=\"profile-photo\">\r\n");
      out.write("                    <img class=\"cv-photo\" src=\"../default-profile.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <label class=\"name-label\">Lorna Nqodi</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"personal-details\">\r\n");
      out.write("                    <label name=\"occupation\">Student</label><br>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <address>\r\n");
      out.write("                      <strong name=\"company\">University of Cape Town</strong><br> <!-- company/institution -->\r\n");
      out.write("                      1355 Market Street, Suite 900<br> <!-- adressline1 -->\r\n");
      out.write("                      CA 94103<br>                      <!-- addressLine2 -->\r\n");
      out.write("                      <abbr title=\"Phone\">P:</abbr> (123) 456-7890\r\n");
      out.write("                  </address>\r\n");
      out.write("              </div>\r\n");
      out.write("              <address>\r\n");
      out.write("                  <a name=\"email\" href=\"mailto:#\">nqdlor001@myuct.ac.za</a>\r\n");
      out.write("              </address>\r\n");
      out.write("                <a  href=\"UpdateProfile.jsp\" class=\"btn btn-default navbar-btn\">Update Profile</a>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"content-offset\">\r\n");
      out.write("          <div class=\"content-frame\"> \r\n");
      out.write("            <div id=\"header\" class=\"row\">\r\n");
      out.write("              <div class=\"header-padding\">\r\n");
      out.write("                <div class=\"header-content\"> <h1>Curriculum Vitae</h1></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\" class=\"row expand\">\r\n");
      out.write("            <form method=\"post\" action=\"../UpdateCV\" >\r\n");
      out.write("          <div class=\"inner-padding\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"section1\" class=\"container-fluid\">\r\n");
      out.write("              <h3 class=\"cv-section\">Education</h3>\r\n");
      out.write("              Highest Degree<br>\r\n");
      out.write("              <input name=\"highestDegree\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Major<br>\r\n");
      out.write("              <input type=\"text\" name=\"major1\" class=\"input-box\"><br>\r\n");
      out.write("              2nd Major (optional)<br>\r\n");
      out.write("              <input name=\"major2\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Institution<br>\r\n");
      out.write("              <input name=\"inst1\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Year of Graduation<br>\r\n");
      out.write("              <input name=\"gradYear\" class=\"input-box\"><br>\r\n");
      out.write("              High School Attended<br>\r\n");
      out.write("              <input name=\"school\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Matric Year<br>\r\n");
      out.write("              <input type=\"text\" name=\"schoolYear\" class=\"input-box\"><br>\r\n");
      out.write("                                                    \r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"section2\" class=\"container-fluid\">\r\n");
      out.write("              <h3 class=\"cv-section\">Work Experience</h3>\r\n");
      out.write("              Job Title<br>\r\n");
      out.write("              <input type=\"text\" name=\"job1\" class=\"input-box\"><br>\r\n");
      out.write("              Company Name or Institution<br>\r\n");
      out.write("              <input type=\"text\" name=\"job1Company\" class=\"input-box\"><br>\r\n");
      out.write("              Year <br>\r\n");
      out.write("              <input type=\"text\" name=\"job1Year\" class=\"input-box\"><br>\r\n");
      out.write("              Job Title<br>\r\n");
      out.write("              <input type=\"text\" name=\"job2\" class=\"input-box\"><br>\r\n");
      out.write("              Company Name or Institution<br>\r\n");
      out.write("              <input name=\"job2Company\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Year <br>\r\n");
      out.write("              <input name=\"job2Year\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("                                 \r\n");
      out.write("          </div>\r\n");
      out.write("        <div id=\"section3\" class=\"container-fluid\">\r\n");
      out.write("         <h3 class=\"cv-section\">Skills</h3>\r\n");
      out.write("         Enter a list of skills you have obtained e.g.(C++, Java, Python)\r\n");
      out.write("         <ol>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill1\" class=\"input-box\"> </li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill2\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill3\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill4\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill5\" class=\"input-box\"> </li>\r\n");
      out.write("         </ol>        \r\n");
      out.write("     </div> \r\n");
      out.write("     <div id=\"section4\" class=\"container-fluid\">\r\n");
      out.write("        <h3 class=\"cv-section\">References</h3>\r\n");
      out.write("        Reference Name<br>\r\n");
      out.write("        <input type=\"text\" name=\"refName1\" class=\"input-box\"><br>\r\n");
      out.write("        Email<br>\r\n");
      out.write("        <input type=\"email\" name=\"refEmail1\" class=\"input-box\"><br>\r\n");
      out.write("        Reference Name<br>\r\n");
      out.write("        <input type=\"text\" name=\"refName2\" class=\"input-box\"><br>\r\n");
      out.write("        Email<br>\r\n");
      out.write("        <input type=\"email\" name=\"refEmail2\" class=\"input-box\"><br>\r\n");
      out.write("     </div> \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
