/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-25 15:32:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.DBUtils;
import java.io.*;
import dao.*;
import java.sql.*;

public final class UpdateCV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");

        if (request.getSession().getAttribute("currentUserName") == null){
        response.sendRedirect("Login.jsp");
    }
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Update CV</title>\r\n");
      out.write("        <!-- css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/normalize.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/nav_style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/site_styles.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/cv.css\">\r\n");
      out.write("        <!-- The fonts-->\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Roboto:100\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- JQuery -->\r\n");
      out.write("        <script src=\"../jQuery/navigation-script.js\"></script>\r\n");
      out.write("        <!-- bootstrap -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"nav-container\" style=\"position:fixed; top:0; left:0; right:0; z-index:1\">\r\n");
      out.write("            <nav class=\"clearfix\">\r\n");
      out.write("                <a href=\"../index.html\" class=\"nav-title\"><img class=\"nav-logo\" src=\"../uct-logo.png\"></a>\r\n");
      out.write("                <span class=\"header-title\" style=\"color:white;\">UCT Alumni Network</span>\r\n");
      out.write("                <ul class=\"clearfix\">\r\n");
      out.write("                    <li><a href=\"../index.html\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span> Home</a></li>\r\n");
      out.write("                    <li><a href=\"CV.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> Profile</a></li>\r\n");
      out.write("                    <li><a href=\"Forum.jsp\"><span class=\"glyphicon glyphicon-comment\" aria-hidden=\"true\"></span> Forum</a></li>\r\n");
      out.write("                    <li><a href=\"\"><span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span> Notifications</a></li>\r\n");
      out.write("                    <li><a href=\"People.jsp\"><span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> People</a></li>            \r\n");
      out.write("                    <li><a href=\"../index.html\"><span class=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span> Logout</a></li> \r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" id=\"pull\">Menu</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"site-wrapper\">\r\n");
      out.write("          <div class=\"site-center\">\r\n");
      out.write("            <div class=\"fixed-wrapper\">\r\n");
      out.write("              <div class=\"fixed-content\">\r\n");
      out.write("    ");
 
            Connection connection = DriverManager.getConnection("jdbc:mysql://137.158.160.145:3306/ngwphu001", "ngwphu001", "eupheyei");

            Statement statement = connection.createStatement() ;
            
            String uid = request.getSession().getAttribute("currentUserID")+"";
            
            ResultSet resultset = statement.executeQuery("SELECT * from CVs WHERE ID = '"+uid+"'") ; 
            resultset.next();
                String fname = resultset.getString(2);
                String lname = resultset.getString(3);
                String occupation = resultset.getString(4);
                String currentCompany = resultset.getString(5);
                String address1 = resultset.getString(6);
                String address2 = resultset.getString(7);
                String city = resultset.getString(8);
                String postalCode = resultset.getString(9);
                String phone = resultset.getString(10);
                String email = resultset.getString(11);
                
                String highestDegree = resultset.getString(12);
                String inst1 = resultset.getString(13);
                String major1 = resultset.getString(14);
                String major2 = resultset.getString(15);
                String gradYear = resultset.getString(16);
                String school = resultset.getString(17);
                String schoolYear = resultset.getString(18);
                String job1 = resultset.getString(19);
                String job1Company = resultset.getString(20);
                String job1Year = resultset.getString(21);
                String job2 = resultset.getString(22);
                String job2Company = resultset.getString(23);
                String job2Year = resultset.getString(24);
                String skill1 = resultset.getString(25);
                String skill2 = resultset.getString(26);
                String skill3 = resultset.getString(27);
                String skill4 = resultset.getString(28);
                String skill5 = resultset.getString(29);
                String refName1 = resultset.getString(30);
                String refEmail1 = resultset.getString(31);
                String refName2 = resultset.getString(32);
                String refEmail2 = resultset.getString(33);
            
        
      out.write("\r\n");
      out.write("                        <div class=\"profile-photo\">\r\n");
      out.write("                            <img class=\"cv-photo\" src=\"../default-profile.png\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label class=\"name-label\">");
      out.print(fname);
      out.write(' ');
      out.write(' ');
      out.print(lname);
      out.write("</label>\r\n");
      out.write("                        <address>\r\n");
      out.write("                          <a href=\"mailto:");
      out.print(email);
      out.write('"');
      out.write('>');
      out.print(email);
      out.write("</a>\r\n");
      out.write("                      </address>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"personal-details\">\r\n");
      out.write("                            <label >");
      out.print(occupation);
      out.write("</label><br>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <address>\r\n");
      out.write("                              <strong>");
      out.print(currentCompany);
      out.write("</strong><br> <!-- company/institution -->\r\n");
      out.write("                              ");
      out.print(address1);
      out.write("<br> <!-- adressline1 -->\r\n");
      out.write("                              ");
      out.print(address2);
      out.write("<br>                      <!-- addressLine2 -->\r\n");
      out.write("                             ");
      out.print(city);
      out.write("<br>\r\n");
      out.write("                              ");
      out.print(postalCode);
      out.write("<br>\r\n");
      out.write("                              <abbr title=\"Phone\">P:</abbr> ");
      out.print(phone);
      out.write("\r\n");
      out.write("                          </address>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("<!--                  <a  href=\"UpdateProfile.jsp\" class=\"btn btn-default navbar-btn\">Update Profile</a>-->\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"content-offset\">\r\n");
      out.write("          <div class=\"content-frame\"> \r\n");
      out.write("            <div id=\"header\" class=\"row\">\r\n");
      out.write("              <div class=\"header-padding\">\r\n");
      out.write("                <div class=\"header-content\"> <h1>Curriculum Vitae</h1></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\" class=\"row expand\">\r\n");
      out.write("            <form method=\"post\" action=\"../UpdateCV\">\r\n");
      out.write("          <div class=\"inner-padding\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"section1\" class=\"container-fluid\">\r\n");
      out.write("              <h3 class=\"cv-section\">Education</h3>\r\n");
      out.write("              Highest Degree<br>\r\n");
      out.write("              <input name=\"highestDegree\" value=\"");
      out.print(highestDegree);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Major<br>\r\n");
      out.write("              <input type=\"text\" value=\"");
      out.print(major1);
      out.write("\" name=\"major1\" class=\"input-box\"><br>\r\n");
      out.write("              2nd Major (optional)<br>\r\n");
      out.write("              <input name=\"major2\" value=\"");
      out.print(major1);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Institution<br>\r\n");
      out.write("              <input name=\"inst1\" value=\"");
      out.print(inst1);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Year of Graduation<br>\r\n");
      out.write("              <input name=\"gradYear\" value=\"");
      out.print(gradYear);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("              High School Attended<br>\r\n");
      out.write("              <input name=\"school\" value=\"");
      out.print(school);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Matric Year<br>\r\n");
      out.write("              <input type=\"text\" name=\"schoolYear\" value=\"");
      out.print(schoolYear);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("                                                    \r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"section2\" class=\"container-fluid\">\r\n");
      out.write("              <h3 class=\"cv-section\">Work Experience</h3>\r\n");
      out.write("              Job Title<br>\r\n");
      out.write("              <input type=\"text\" name=\"job1\" value=\"");
      out.print(job1);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("              Company Name or Institution<br>\r\n");
      out.write("              <input type=\"text\" name=\"job1Company\" value=\"");
      out.print(job1Company);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("              Year <br>\r\n");
      out.write("              <input type=\"text\" name=\"job1Year\" value=\"");
      out.print(job1Year);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("              Job Title<br>\r\n");
      out.write("              <input type=\"text\" name=\"job2\" value=\"");
      out.print(job2);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("              Company Name or Institution<br>\r\n");
      out.write("              <input name=\"job2Company\" value=\"");
      out.print(job2Company);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("              Year <br>\r\n");
      out.write("              <input name=\"job2Year\" value=\"");
      out.print(job2Year);
      out.write("\" type=\"text\" class=\"input-box\"><br>\r\n");
      out.write("                                 \r\n");
      out.write("          </div>\r\n");
      out.write("        <div id=\"section3\" class=\"container-fluid\">\r\n");
      out.write("         <h3 class=\"cv-section\">Skills</h3>\r\n");
      out.write("         Enter a list of skills you have obtained e.g.(C++, Java, Python)\r\n");
      out.write("         <ol>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill1\" value=\"");
      out.print(skill1);
      out.write("\" class=\"input-box\"> </li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill2\" value=\"");
      out.print(skill2);
      out.write("\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill3\" value=\"");
      out.print(skill3);
      out.write("\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill4\" value=\"");
      out.print(skill4);
      out.write("\" class=\"input-box\"></li>\r\n");
      out.write("             <li><input type=\"text\" name=\"skill5\" value=\"");
      out.print(skill5);
      out.write("\" class=\"input-box\"> </li>\r\n");
      out.write("         </ol>        \r\n");
      out.write("     </div> \r\n");
      out.write("     <div id=\"section4\" class=\"container-fluid\">\r\n");
      out.write("        <h3 class=\"cv-section\">References</h3>\r\n");
      out.write("        Reference Name<br>\r\n");
      out.write("        <input type=\"text\" name=\"refName1\" value=\"");
      out.print(refName1);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("        Email<br>\r\n");
      out.write("        <input type=\"email\" name=\"refEmail1\" value=\"");
      out.print(refEmail1);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("        Reference Name<br>\r\n");
      out.write("        <input type=\"text\" name=\"refName2\" value=\"");
      out.print(refName2);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("        Email<br>\r\n");
      out.write("        <input type=\"email\" name=\"refEmail2\" value=\"");
      out.print(refEmail2);
      out.write("\" class=\"input-box\"><br>\r\n");
      out.write("        <button style=\"border: 2px solid #D84D0A; font-size:15px; border-radius:3px; margin-top:5px;\" type=\"submit\">Save changes</button>\r\n");
      out.write("     </div> \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
